-- MySQL Script generated by MySQL Workbench
-- Mon Sep  3 08:11:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paciente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `idpaciente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `eps` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaciente`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cita` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cita` (
  `idcita` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `disponibilidad` TINYINT NOT NULL,
  `costo` DOUBLE NOT NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idcita`, `paciente_idpaciente`),
  INDEX `fk_cita_paciente1_idx` (`paciente_idpaciente` ASC),
  CONSTRAINT `fk_cita_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formula` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formula` (
  `idformula` INT NOT NULL,
  `tratamiento` VARCHAR(5000) NOT NULL,
  `fecha` DATE NULL,
  `observacion` TEXT NULL,
  `cita_idcita` INT NOT NULL,
  `cita_paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idformula`),
  INDEX `fk_formula_cita1_idx` (`cita_idcita` ASC, `cita_paciente_idpaciente` ASC),
  CONSTRAINT `fk_formula_cita1`
    FOREIGN KEY (`cita_idcita` , `cita_paciente_idpaciente`)
    REFERENCES `mydb`.`cita` (`idcita` , `paciente_idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cartera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cartera` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cartera` (
  `idcartera` INT NOT NULL,
  `carteracol` VARCHAR(45) NULL,
  `costo_cita` DOUBLE NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idcartera`),
  INDEX `fk_cartera_paciente1_idx` (`paciente_idpaciente` ASC),
  CONSTRAINT `fk_cartera_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historia_clinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`historia_clinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`historia_clinica` (
  `idhistoria_clinica` INT NOT NULL,
  `observaciones` TEXT NOT NULL,
  `alergia` VARCHAR(500) NOT NULL,
  `tratamiento` TEXT NOT NULL,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idhistoria_clinica`),
  INDEX `fk_historia_clinica_paciente1_idx` (`paciente_idpaciente` ASC),
  CONSTRAINT `fk_historia_clinica_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `mydb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL,
  `total_productos` INT NOT NULL,
  `total_costo` DOUBLE NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(500) NOT NULL,
  `contrasena_usuario` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`acceso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`acceso` (
  `idacceso` INT NOT NULL,
  `fecha_acceso` DATETIME NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idacceso`),
  INDEX `fk_acceso_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_acceso_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `idproducto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `proveedor` VARCHAR(500) NOT NULL,
  `disponibilidad` VARCHAR(45) NOT NULL,
  `inventario_idinventario` INT NOT NULL,
  `formula_idformula` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_inventario1_idx` (`inventario_idinventario` ASC),
  INDEX `fk_producto_formula1_idx` (`formula_idformula` ASC),
  CONSTRAINT `fk_producto_inventario1`
    FOREIGN KEY (`inventario_idinventario`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_formula1`
    FOREIGN KEY (`formula_idformula`)
    REFERENCES `mydb`.`formula` (`idformula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
